### ISSUE TITLE
Minor problem in Documentation causes "Error: error: Expected '>', got 'spec'" for SwaggerUI component in next.js

### ISSUE THREAD

**Issue by joergrech** [jellydn/next-swagger-doc#180]
I just started with the example and created a file "api-doc.ts" and copied the code from the npm page. This causes the following problem:
```
Error: error: Expected '>', got 'spec'
 
  |
8 |   return <SwaggerUI spec={ spec } />
  |                     ^^^^

Caused by:
    0: failed to process js file
    1: Syntax Error
```
After a little googling I found out that the file should be called "api-doc.tsx" (using the extension "tsx" not "ts") and then it will compile.

**Comment by jellydn** [comment]
Hi @joergrech for filing the issue but I think that's fixed by this PR https://github.com/jellydn/next-swagger-doc/pull/173

You're right. That's a `tsx` file.

**Comment by joergrech** [comment]
From what I see it is/was correct in Github but is still incorrect in npm (see https://www.npmjs.com/package/next-swagger-doc). It might let newbies run into the same problem as I have.
Nevertheless, many thanks for your work!
